"""Add profile_image to User

Revision ID: 1ed952ce63f6
Revises: 98956502112f
Create Date: 2025-08-18 02:49:08.677505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed952ce63f6'
down_revision = '98956502112f'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=150), nullable=True))
    
    op.execute("UPDATE user SET profile_image = 'default.png' WHERE profile_image IS NULL")
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('profile_image', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
