"""Add date_joined to User

Revision ID: 98956502112f
Revises: 
Create Date: 2025-08-16 11:33:32.410881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98956502112f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
